// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4uwNRaUd-x6XrMB1UKuvXjfNE3ojyIK8',
    appId: '1:229940913911:web:1f7dab558e9f819e53d5f2',
    messagingSenderId: '229940913911',
    projectId: 'bb-anamak-ai',
    authDomain: 'bb-anamak-ai.firebaseapp.com',
    storageBucket: 'bb-anamak-ai.firebasestorage.app',
    measurementId: 'G-YSWBR7N96Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDntAAdrYghH9tfW9JbxKwvPtAbYK7kaTM',
    appId: '1:229940913911:android:b4721fabfb0768d053d5f2',
    messagingSenderId: '229940913911',
    projectId: 'bb-anamak-ai',
    storageBucket: 'bb-anamak-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM1D3XIQOWPynsdI7HMY9aC9V29w8OPHE',
    appId: '1:229940913911:ios:dbd9abb08a7c805e53d5f2',
    messagingSenderId: '229940913911',
    projectId: 'bb-anamak-ai',
    storageBucket: 'bb-anamak-ai.firebasestorage.app',
    androidClientId:
        '229940913911-44e11cpqa3g5u1d6hsrtj7nppmbg2seq.apps.googleusercontent.com',
    iosClientId:
        '229940913911-3806010nbftcr93vgrqvpls9r7o08aji.apps.googleusercontent.com',
    iosBundleId: 'com.bb.myhisaab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM1D3XIQOWPynsdI7HMY9aC9V29w8OPHE',
    appId: '1:229940913911:ios:daf38bb92ded32d653d5f2',
    messagingSenderId: '229940913911',
    projectId: 'bb-anamak-ai',
    storageBucket: 'bb-anamak-ai.firebasestorage.app',
    androidClientId:
        '229940913911-44e11cpqa3g5u1d6hsrtj7nppmbg2seq.apps.googleusercontent.com',
    iosClientId:
        '229940913911-pls8ee4oi4idgd8s7jtnv1jfa6mjnuuf.apps.googleusercontent.com',
    iosBundleId: 'com.example.myselfDiary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4uwNRaUd-x6XrMB1UKuvXjfNE3ojyIK8',
    appId: '1:229940913911:web:005c392262aa534b53d5f2',
    messagingSenderId: '229940913911',
    projectId: 'bb-anamak-ai',
    authDomain: 'bb-anamak-ai.firebaseapp.com',
    storageBucket: 'bb-anamak-ai.firebasestorage.app',
    measurementId: 'G-K1W66S3SRS',
  );
}
