// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_zTkpdweOZAV36jLf4m6ToIF-QDEgIuQ',
    appId: '1:366344398783:web:4f59ab13a0793f4c4e630a',
    messagingSenderId: '366344398783',
    projectId: 'hisaab-ee9ad',
    authDomain: 'hisaab-ee9ad.firebaseapp.com',
    storageBucket: 'hisaab-ee9ad.appspot.com',
    measurementId: 'G-025KFR9FQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxpYyQNG_jOPzRLdJzaZRTSHQ3HaRcc1k',
    appId: '1:366344398783:android:d8eada06f5a10a3d4e630a',
    messagingSenderId: '366344398783',
    projectId: 'hisaab-ee9ad',
    storageBucket: 'hisaab-ee9ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrYYiTzqWlRCd-heaFtwBy4t0VHVTT7GI',
    appId: '1:366344398783:ios:68f506aebbeac0da4e630a',
    messagingSenderId: '366344398783',
    projectId: 'hisaab-ee9ad',
    storageBucket: 'hisaab-ee9ad.appspot.com',
    iosClientId: '366344398783-fb0qssph4boom6pgt4kvsjfhrir7igvb.apps.googleusercontent.com',
    iosBundleId: 'com.prod.myhisaab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrYYiTzqWlRCd-heaFtwBy4t0VHVTT7GI',
    appId: '1:366344398783:ios:6b396e16d3b9f27e4e630a',
    messagingSenderId: '366344398783',
    projectId: 'hisaab-ee9ad',
    storageBucket: 'hisaab-ee9ad.appspot.com',
    iosClientId: '366344398783-d8alm1bk301d1518t620067skmb9dg7o.apps.googleusercontent.com',
    iosBundleId: 'com.example.myHisaab.RunnerTests',
  );
}
